"""
Data Ingestion, Validation, and Reconciliation Pipeline
========================================================

PURPOSE
-------
Loads paid-media campaign exports (Bing/Google/Meta), GA4 session data, and
Shopify order data; normalizes everything onto a common join key (date +
channel grouping); runs a battery of validation checks -- including the
campaign-naming-consistency checks called out in the brief -- and produces a
full reconciliation comparing what the ad platforms self-report against what
GA4 sessions and Shopify orders actually show.

NOTE ON DATA SOURCES
---------------------
No real GA4 property or Shopify store was available for this project (see
the data-sourcing discussion). `load_ga4_sessions()` and `load_shopify_orders()`
below read synthetic-but-campaign-consistent CSVs generated by
`generate_synthetic_data.py` -- same dates, same channel groupings as the
real Bing/Google/Meta exports, so the join keys line up. The loaders are
written against a plain, generic schema (date/channel grouping/sessions and
order_date/channel_grouping/revenue) so swapping in a real GA4 export or a
real Shopify order export later only requires matching column names, not a
rewrite of the pipeline.

USAGE
-----
    python ingest_validate_reconcile.py \
        --bing bing_campaign_stats.csv \
        --google google_ads_campaign_stats.csv \
        --meta meta_ads_campaign_stats.csv \
        --ga4 synthetic_ga4_sessions.csv \
        --shopify synthetic_shopify_orders.csv \
        --outdir ./output

Outputs:
    output/unified_campaign_data.csv         - normalized ad-platform dataset
    output/channel_reconciliation.csv        - date+channel grain: ad vs GA4 vs Shopify
    output/reconciliation_monthly_summary.csv- ad-platform monthly totals
    output/validation_report.json            - structured findings (machine readable)
    output/validation_report.txt             - human-readable summary
"""

import argparse
import json
import re
from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------------------
# 1. CONFIG / COMMON SCHEMA
# ---------------------------------------------------------------------------

UNIFIED_COLUMNS = [
    "date", "platform", "campaign_id", "campaign_name", "native_channel_type",
    "channel_grouping", "audience_tag", "campaign_number",
    "impressions", "clicks", "spend", "conversions", "revenue", "daily_budget",
    "join_key",
]

# Expected naming convention across all platforms:
#   <Base>[_<TM|NTM>]_Campaign_<NN>
# e.g. "Search_TM_Campaign_02", "Pmax_NTM_Campaign_11", "Generic_Campaign_01"
NAME_PATTERN = re.compile(r"^(?P<prefix>.+?)_Campaign_(?P<num>\d+)$")
AUDIENCE_SUFFIX_PATTERN = re.compile(r"^(?P<base>.+)_(?P<tag>TM|NTM)$")


# ---------------------------------------------------------------------------
# 2. LOADERS  (one per platform -> normalized DataFrame)
# ---------------------------------------------------------------------------

def load_bing(path: str) -> pd.DataFrame:
    raw = pd.read_csv(path)
    df = pd.DataFrame({
        "date": pd.to_datetime(raw["TimePeriod"], errors="coerce"),
        "platform": "Bing Ads",
        "campaign_id": raw["CampaignId"].astype(str),
        "campaign_name": raw["CampaignName"].astype(str),
        "native_channel_type": raw["CampaignType"].astype(str),
        "impressions": raw["Impressions"],
        "clicks": raw["Clicks"],
        "spend": raw["Spend"],
        "conversions": raw["Conversions"],
        "revenue": raw["Revenue"],
        "daily_budget": raw["DailyBudget"],
    })
    return df


def load_google_ads(path: str) -> pd.DataFrame:
    raw = pd.read_csv(path)
    df = pd.DataFrame({
        "date": pd.to_datetime(raw["segments_date"], errors="coerce"),
        "platform": "Google Ads",
        "campaign_id": raw["campaign_id"].astype(str),
        "campaign_name": raw["campaign_name"].astype(str),
        "native_channel_type": raw["campaign_advertising_channel_type"].astype(str),
        "impressions": raw["metrics_impressions"],
        "clicks": raw["metrics_clicks"],
        "spend": raw["metrics_cost_micros"] / 1_000_000.0,  # micros -> currency
        "conversions": raw["metrics_conversions"],
        "revenue": raw["metrics_conversions_value"],
        "daily_budget": raw["campaign_budget_amount"],
    })
    return df


def load_meta_ads(path: str) -> pd.DataFrame:
    raw = pd.read_csv(path)
    df = pd.DataFrame({
        "date": pd.to_datetime(raw["date_start"], errors="coerce"),
        "platform": "Meta Ads",
        "campaign_id": raw["campaign_id"].astype(str),
        "campaign_name": raw["campaign_name"].astype(str),
        "native_channel_type": pd.NA,  # Meta export has no campaign-type column
        "impressions": raw["impressions"],
        "clicks": raw["clicks"],
        "spend": raw["spend"],
        "conversions": raw["conversion"],
        "revenue": pd.NA,  # Meta export has no revenue/conversion-value column
        "daily_budget": raw["daily_budget"],
    })
    return df


PLATFORM_LOADERS = {
    "Bing Ads": load_bing,
    "Google Ads": load_google_ads,
    "Meta Ads": load_meta_ads,
}


# ---------------------------------------------------------------------------
# 3. CAMPAIGN NAME PARSING + JOIN KEY
# ---------------------------------------------------------------------------

def parse_campaign_name(name: str) -> dict:
    """Break a campaign name into (channel_grouping, audience_tag, number).

    Returns a dict with `valid=False` if the name does not match the
    expected `<Base>[_<TM|NTM>]_Campaign_<NN>` convention at all.
    """
    m = NAME_PATTERN.match(name.strip())
    if not m:
        return {"valid": False, "base": None, "audience_tag": None, "number": None}

    prefix, num = m.group("prefix"), m.group("num")
    tag_match = AUDIENCE_SUFFIX_PATTERN.match(prefix)
    if tag_match:
        base, tag = tag_match.group("base"), tag_match.group("tag")
    else:
        base, tag = prefix, None

    return {"valid": True, "base": base, "audience_tag": tag, "number": num}


def add_derived_fields(df: pd.DataFrame) -> pd.DataFrame:
    parsed = df["campaign_name"].apply(parse_campaign_name).apply(pd.Series)
    df["channel_grouping"] = parsed["base"]
    df["audience_tag"] = parsed["audience_tag"]
    df["campaign_number"] = parsed["number"]
    df["_name_valid"] = parsed["valid"]

    # Join key: date + channel grouping. This is the cross-platform key the
    # brief calls for (date + channel grouping derived from naming/UTM).
    # Falls back to "UNPARSED" so malformed names still produce a key rather
    # than silently dropping rows from the join.
    grouping = df["channel_grouping"].fillna("UNPARSED")
    df["join_key"] = df["date"].dt.strftime("%Y-%m-%d") + "|" + grouping
    return df


# ---------------------------------------------------------------------------
# 4. VALIDATION CHECKS
# ---------------------------------------------------------------------------
# Each check returns a dict: {"check": name, "status": "pass"/"fail",
# "issue_count": n, "details": [...]}. Keeping every check in this uniform
# shape makes the report easy to scan and easy to extend.

def check_required_columns(df: pd.DataFrame) -> dict:
    missing = [c for c in UNIFIED_COLUMNS if c not in df.columns]
    return {
        "check": "required_columns_present",
        "status": "pass" if not missing else "fail",
        "issue_count": len(missing),
        "details": missing,
    }


def check_missing_critical_values(df: pd.DataFrame) -> dict:
    critical = ["date", "platform", "campaign_id", "campaign_name", "spend"]
    nulls = df[critical].isnull().sum()
    nulls = nulls[nulls > 0]
    return {
        "check": "missing_critical_values",
        "status": "pass" if nulls.empty else "fail",
        "issue_count": int(nulls.sum()),
        "details": nulls.to_dict(),
    }


def check_duplicate_grain(df: pd.DataFrame) -> dict:
    dupes = df.duplicated(subset=["platform", "campaign_id", "date"]).sum()
    return {
        "check": "duplicate_platform_campaign_date_rows",
        "status": "pass" if dupes == 0 else "fail",
        "issue_count": int(dupes),
        "details": f"{dupes} duplicate (platform, campaign_id, date) rows found",
    }


def check_negative_metrics(df: pd.DataFrame) -> dict:
    metrics = ["impressions", "clicks", "spend", "conversions"]
    issues = {}
    for m in metrics:
        n = (df[m].dropna() < 0).sum()
        if n:
            issues[m] = int(n)
    return {
        "check": "negative_metric_values",
        "status": "pass" if not issues else "fail",
        "issue_count": sum(issues.values()),
        "details": issues,
    }


def check_clicks_exceed_impressions(df: pd.DataFrame) -> dict:
    bad = df[df["clicks"] > df["impressions"]]
    return {
        "check": "clicks_exceed_impressions",
        "status": "pass" if bad.empty else "fail",
        "issue_count": len(bad),
        "details": bad[["platform", "campaign_id", "campaign_name", "date"]]
        .head(10).astype(str).to_dict(orient="records"),
    }


def check_conversions_exceed_clicks(df: pd.DataFrame) -> dict:
    bad = df[df["conversions"] > df["clicks"]]
    return {
        "check": "conversions_exceed_clicks",
        "status": "pass" if bad.empty else "warn",
        "issue_count": len(bad),
        "details": (
            f"{len(bad)} rows where conversions > clicks. This can be "
            "legitimate (multi-touch/view-through attribution) but should "
            "be confirmed against the attribution model in use."
        ),
    }


def check_campaign_naming_pattern(df: pd.DataFrame) -> dict:
    bad = df.loc[~df["_name_valid"], ["platform", "campaign_id", "campaign_name"]].drop_duplicates()
    return {
        "check": "campaign_naming_pattern_compliance",
        "status": "pass" if bad.empty else "fail",
        "issue_count": len(bad),
        "details": bad.astype(str).to_dict(orient="records"),
    }


def check_naming_delimiter_consistency(df: pd.DataFrame) -> dict:
    """Flag channel-grouping tokens that mix a space-delimited word into an
    otherwise underscore-delimited naming convention (e.g. 'Demand Gen' vs
    'Search', 'Pmax', 'Shopping')."""
    groupings = df["channel_grouping"].dropna().unique()
    inconsistent = sorted(g for g in groupings if " " in str(g))
    return {
        "check": "naming_delimiter_consistency",
        "status": "pass" if not inconsistent else "warn",
        "issue_count": len(inconsistent),
        "details": (
            f"Channel grouping token(s) {inconsistent} use a space instead "
            "of the underscore delimiter used elsewhere in the naming "
            "convention (e.g. 'Search', 'Pmax', 'Shopping')."
            if inconsistent else ""
        ),
    }


def check_id_name_one_to_one(df: pd.DataFrame) -> dict:
    """A campaign_id should map to exactly one campaign_name (and vice
    versa) within a platform. Renames/ID-reuse over time would break joins
    silently if not caught here."""
    issues = []
    for platform, sub in df.groupby("platform"):
        ids_per_name = sub.groupby("campaign_name")["campaign_id"].nunique()
        names_per_id = sub.groupby("campaign_id")["campaign_name"].nunique()
        bad_names = ids_per_name[ids_per_name > 1]
        bad_ids = names_per_id[names_per_id > 1]
        for name, n in bad_names.items():
            issues.append(f"[{platform}] name '{name}' maps to {n} different campaign_ids")
        for cid, n in bad_ids.items():
            issues.append(f"[{platform}] campaign_id '{cid}' maps to {n} different names")
    return {
        "check": "campaign_id_name_one_to_one",
        "status": "pass" if not issues else "fail",
        "issue_count": len(issues),
        "details": issues,
    }


def check_name_to_native_type_alignment(df: pd.DataFrame) -> dict:
    """For each (platform, channel_grouping), the native platform type field
    should be a single consistent value. If a channel_grouping maps to more
    than one native_channel_type within the same platform, the name and the
    underlying campaign type have drifted out of sync -- this is the
    Bing 'Demand Gen' (named) vs 'Audience' (actual type) case."""
    issues = []
    for (platform, grouping), sub in df.dropna(subset=["channel_grouping"]).groupby(
        ["platform", "channel_grouping"]
    ):
        native_types = sub["native_channel_type"].dropna().unique()
        if len(native_types) > 1:
            issues.append(
                f"[{platform}] campaigns named '{grouping}_...' have inconsistent "
                f"native types: {list(native_types)}"
            )
    return {
        "check": "name_to_native_type_alignment",
        "status": "pass" if not issues else "fail",
        "issue_count": len(issues),
        "details": issues,
    }


def check_cross_platform_type_label_drift(df: pd.DataFrame) -> dict:
    """Informational: shows, for each channel_grouping, what native type
    label each platform actually uses underneath it. Surfaces cases like
    Bing's campaigns literally named 'Demand Gen' being tagged internally
    as 'Audience' rather than a Demand-Gen-equivalent type, even though
    Google's 'Demand Gen'-named campaigns are correctly tagged DEMAND_GEN."""
    table = (
        df.dropna(subset=["channel_grouping"])
        .groupby(["channel_grouping", "platform"])["native_channel_type"]
        .agg(lambda s: sorted(s.dropna().unique().tolist()))
        .reset_index()
    )
    mismatches = []
    for grouping, sub in table.groupby("channel_grouping"):
        flat = {row["platform"]: row["native_channel_type"] for _, row in sub.iterrows()}
        mismatches.append({"channel_grouping": grouping, "native_type_by_platform": flat})
    return {
        "check": "cross_platform_type_label_drift (informational)",
        "status": "info",
        "issue_count": len(mismatches),
        "details": mismatches,
    }


def check_numbering_padding(df: pd.DataFrame) -> dict:
    """Campaign numbers should use consistent zero-padding width within a
    given (platform, channel_grouping) so sorts/joins by suffix don't break."""
    issues = []
    sub = df.dropna(subset=["channel_grouping", "campaign_number"])
    for (platform, grouping), grp in sub.groupby(["platform", "channel_grouping"]):
        widths = grp["campaign_number"].astype(str).str.len().unique()
        if len(widths) > 1:
            issues.append(
                f"[{platform}] '{grouping}' campaigns use inconsistent number "
                f"padding widths: {sorted(widths.tolist())}"
            )
    return {
        "check": "campaign_number_padding_consistency",
        "status": "pass" if not issues else "warn",
        "issue_count": len(issues),
        "details": issues,
    }


def check_date_gaps(df: pd.DataFrame) -> dict:
    """Within each campaign's active date range, flag missing calendar
    days. A handful of gaps can be normal (paused campaigns); large gaps
    are worth a second look."""
    issues = []
    for (platform, cid, name), grp in df.groupby(["platform", "campaign_id", "campaign_name"]):
        full_range = pd.date_range(grp["date"].min(), grp["date"].max(), freq="D")
        missing = full_range.difference(grp["date"])
        if len(missing) > 0:
            issues.append({
                "platform": platform,
                "campaign_id": cid,
                "campaign_name": name,
                "missing_days": len(missing),
                "active_span_days": len(full_range),
            })
    issues.sort(key=lambda x: x["missing_days"], reverse=True)
    return {
        "check": "date_coverage_gaps",
        "status": "pass" if not issues else "warn",
        "issue_count": len(issues),
        "details": issues[:15],  # top offenders only, to keep the report readable
    }


VALIDATION_CHECKS = [
    check_required_columns,
    check_missing_critical_values,
    check_duplicate_grain,
    check_negative_metrics,
    check_clicks_exceed_impressions,
    check_conversions_exceed_clicks,
    check_campaign_naming_pattern,
    check_naming_delimiter_consistency,
    check_id_name_one_to_one,
    check_name_to_native_type_alignment,
    check_cross_platform_type_label_drift,
    check_numbering_padding,
    check_date_gaps,
]


# ---------------------------------------------------------------------------
# 5. RECONCILIATION SUMMARY (cross-platform totals)
# ---------------------------------------------------------------------------

def build_reconciliation_summary(df: pd.DataFrame) -> pd.DataFrame:
    """Monthly totals per platform -- the baseline view you'd cross-check
    against platform UI exports or, once available, against GA4/Shopify."""
    summary = df.copy()
    summary["month"] = summary["date"].dt.to_period("M").astype(str)
    out = (
        summary.groupby(["platform", "month"])
        .agg(
            spend=("spend", "sum"),
            clicks=("clicks", "sum"),
            impressions=("impressions", "sum"),
            conversions=("conversions", "sum"),
            revenue=("revenue", "sum"),
        )
        .reset_index()
        .sort_values(["platform", "month"])
    )
    return out


# ---------------------------------------------------------------------------
# 6. GA4 SESSIONS + SHOPIFY ORDERS  (loaders + aggregation to join_key grain)
# ---------------------------------------------------------------------------
# Expected schemas (matching what generate_synthetic_data.py produces, and
# what a real export would need to provide):
#   GA4 sessions:   date, channel_grouping, sessions, avg_session_duration,
#                   engagement_rate  (platform/campaign_name/session_source_medium
#                   are carried through if present but not required)
#   Shopify orders: order_id, order_date, channel_grouping, revenue
#                   (utm_source/utm_medium/platform/campaign_name optional)
#
# Real GA4: channel_grouping would be derived from (sessionSource, sessionMedium)
# via the same kind of mapping used in generate_synthetic_data.py's
# get_source_medium(), inverted. Real Shopify: channel_grouping would come from
# parsing the order's UTM campaign field (or customer_journey_summary) the same
# way ad campaign names are parsed here.

def load_ga4_sessions(path: str) -> pd.DataFrame:
    raw = pd.read_csv(path)
    raw["date"] = pd.to_datetime(raw["date"], errors="coerce")
    required = {"date", "channel_grouping", "sessions"}
    missing = required - set(raw.columns)
    if missing:
        raise ValueError(f"GA4 sessions file is missing required columns: {missing}")
    if "join_key" not in raw.columns:
        raw["join_key"] = raw["date"].dt.strftime("%Y-%m-%d") + "|" + raw["channel_grouping"]
    return raw


def load_shopify_orders(path: str) -> pd.DataFrame:
    raw = pd.read_csv(path)
    raw["order_date"] = pd.to_datetime(raw["order_date"], errors="coerce")
    required = {"order_date", "channel_grouping", "revenue"}
    missing = required - set(raw.columns)
    if missing:
        raise ValueError(f"Shopify orders file is missing required columns: {missing}")
    if "join_key" not in raw.columns:
        raw["join_key"] = raw["order_date"].dt.strftime("%Y-%m-%d") + "|" + raw["channel_grouping"]
    return raw


def aggregate_ad_data(df: pd.DataFrame) -> pd.DataFrame:
    """Ad-platform data to join_key grain (date + channel_grouping, summed
    across platforms/campaigns that share a grouping on the same day)."""
    return (
        df.groupby("join_key")
        .agg(
            date=("date", "first"),
            channel_grouping=("channel_grouping", "first"),
            ad_clicks=("clicks", "sum"),
            ad_impressions=("impressions", "sum"),
            ad_spend=("spend", "sum"),
            ad_conversions=("conversions", "sum"),
            ad_revenue=("revenue", "sum"),
        )
        .reset_index()
    )


def aggregate_ga4_data(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby("join_key")
        .agg(
            ga4_sessions=("sessions", "sum"),
            avg_session_duration=("avg_session_duration", "mean"),
            engagement_rate=("engagement_rate", "mean"),
        )
        .reset_index()
    )


def aggregate_shopify_data(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby("join_key")
        .agg(
            shopify_orders=("order_id", "count") if "order_id" in df.columns else ("revenue", "count"),
            shopify_revenue=("revenue", "sum"),
        )
        .reset_index()
    )


def build_channel_reconciliation(ad_df: pd.DataFrame, ga4_df: pd.DataFrame, shopify_df: pd.DataFrame) -> pd.DataFrame:
    """The core reconciliation table: one row per (date, channel_grouping),
    with ad-platform-reported metrics sitting next to GA4 sessions and
    Shopify orders/revenue for the same key. This is what makes discrepancies
    visible -- a join_key with ad_clicks but no ga4_sessions, or ad_conversions
    that don't match shopify_orders, shows up directly as null/mismatched
    columns in one row instead of being buried in three separate files."""
    ad_agg = aggregate_ad_data(ad_df)
    ga4_agg = aggregate_ga4_data(ga4_df)
    shopify_agg = aggregate_shopify_data(shopify_df)

    merged = ad_agg.merge(ga4_agg, on="join_key", how="outer").merge(shopify_agg, on="join_key", how="outer")

    # date/channel_grouping may be null on rows that only exist in GA4/Shopify
    # (e.g. organic channels with no ad spend) -- backfill from the join_key.
    key_split = merged["join_key"].str.split("|", n=1, expand=True)
    merged["date"] = merged["date"].fillna(pd.to_datetime(key_split[0]))
    merged["channel_grouping"] = merged["channel_grouping"].fillna(key_split[1])

    merged["session_to_click_ratio"] = merged["ga4_sessions"] / merged["ad_clicks"]
    merged["conversion_gap"] = merged["ad_conversions"] - merged["shopify_orders"]
    merged["conversion_gap_pct"] = (
        merged["conversion_gap"] / merged["ad_conversions"].replace(0, pd.NA) * 100
    )
    merged["revenue_gap"] = merged["ad_revenue"] - merged["shopify_revenue"]
    merged["revenue_gap_pct"] = merged["revenue_gap"] / merged["ad_revenue"].replace(0, pd.NA) * 100

    cols = [
        "join_key", "date", "channel_grouping",
        "ad_clicks", "ad_impressions", "ad_spend", "ad_conversions", "ad_revenue",
        "ga4_sessions", "avg_session_duration", "engagement_rate", "session_to_click_ratio",
        "shopify_orders", "shopify_revenue", "conversion_gap", "conversion_gap_pct",
        "revenue_gap", "revenue_gap_pct",
    ]
    return merged[cols].sort_values(["date", "channel_grouping"]).reset_index(drop=True)


# ---------------------------------------------------------------------------
# 6b. RECONCILIATION-LEVEL VALIDATION CHECKS
# ---------------------------------------------------------------------------

def check_ga4_join_coverage(recon: pd.DataFrame) -> dict:
    """Of the join_keys with real ad spend (paid channels), what fraction
    have any matching GA4 session data at all?"""
    paid = recon[recon["ad_clicks"].fillna(0) > 0]
    missing = paid[paid["ga4_sessions"].isna()]
    pct = 100 * len(missing) / len(paid) if len(paid) else 0
    return {
        "check": "ga4_join_coverage",
        "status": "pass" if missing.empty else ("fail" if pct > 5 else "warn"),
        "issue_count": len(missing),
        "details": f"{len(missing)} of {len(paid)} paid (date, channel_grouping) keys "
                   f"({pct:.1f}%) have ad spend but no matching GA4 session data.",
    }


def check_shopify_join_coverage(recon: pd.DataFrame) -> dict:
    """Of the join_keys with real ad spend, what fraction have any matching
    Shopify order data at all? (Some zero-conversion days are expected and
    fine; widespread gaps point to a UTM/attribution problem.)"""
    paid = recon[recon["ad_clicks"].fillna(0) > 0]
    missing = paid[paid["shopify_orders"].isna()]
    pct = 100 * len(missing) / len(paid) if len(paid) else 0
    return {
        "check": "shopify_join_coverage",
        "status": "pass" if pct < 20 else ("fail" if pct > 60 else "warn"),
        "issue_count": len(missing),
        "details": f"{len(missing)} of {len(paid)} paid (date, channel_grouping) keys "
                   f"({pct:.1f}%) have ad spend but no matching Shopify order data.",
    }


def check_session_click_ratio_outliers(recon: pd.DataFrame) -> dict:
    """Sessions per click should sit in a plausible band (roughly 0.1x-3x).
    Values far outside that suggest a broken UTM tag, a tracking gap, or
    bot/click-fraud traffic worth investigating on a specific campaign."""
    sub = recon.dropna(subset=["session_to_click_ratio"])
    bad = sub[(sub["session_to_click_ratio"] < 0.1) | (sub["session_to_click_ratio"] > 3.0)]
    return {
        "check": "session_to_click_ratio_outliers",
        "status": "pass" if bad.empty else "warn",
        "issue_count": len(bad),
        "details": bad[["date", "channel_grouping", "ad_clicks", "ga4_sessions", "session_to_click_ratio"]]
        .head(10).astype(str).to_dict(orient="records"),
    }


META_ONLY_GROUPINGS = {
    "Generic", "Generic_Brand", "Prospecting_DPA", "Prospecting_Brand",
    "Prospecting_Adv_Plus", "Remarketing_DPA", "Remarketing_Brand",
}


def check_conversion_discrepancy(recon: pd.DataFrame) -> dict:
    """Headline reconciliation metric: total ad-platform-reported conversions
    vs. total Shopify orders. Broken out by platform group rather than
    reported as one blended number, because Meta's channel groupings and
    Bing/Google's channel groupings don't overlap, and Meta's own
    'conversion' figure is several times its own click count (so it can't
    be a literal order count) -- blending it into one total would make the
    Bing/Google comparison, which is far more trustworthy, invisible."""
    bg = recon[~recon["channel_grouping"].isin(META_ONLY_GROUPINGS)]
    meta = recon[recon["channel_grouping"].isin(META_ONLY_GROUPINGS)]

    def gap(sub):
        ad, orders = sub["ad_conversions"].sum(), sub["shopify_orders"].sum()
        pct = 100 * (ad - orders) / ad if ad else 0
        return ad, orders, pct

    bg_ad, bg_orders, bg_pct = gap(bg)
    meta_ad, meta_orders, meta_pct = gap(meta)
    status = "pass" if abs(bg_pct) < 10 else ("warn" if abs(bg_pct) < 40 else "fail")

    return {
        "check": "ad_platform_vs_shopify_conversion_discrepancy",
        "status": status,
        "issue_count": 1 if status != "pass" else 0,
        "details": (
            f"Bing+Google: {bg_ad:,.0f} reported conversions vs {bg_orders:,.0f} Shopify orders "
            f"({bg_pct:+.1f}% gap). Meta: {meta_ad:,.0f} reported 'conversions' vs {meta_orders:,.0f} "
            f"Shopify orders ({meta_pct:+.1f}% gap) -- Meta's figure is not comparable to the others "
            f"(it exceeds Meta's own click count), so its gap is reported separately rather than "
            f"blended into one misleading total."
        ),
    }


def check_revenue_discrepancy(recon: pd.DataFrame) -> dict:
    """Same idea for revenue, restricted to channel groupings where the ad
    platform actually reports a revenue figure (Bing and Google do; Meta's
    export has no revenue field at all, so it's naturally excluded here --
    every channel grouping with a non-null ad_revenue is Bing/Google)."""
    sub = recon.dropna(subset=["ad_revenue"])
    total_ad_rev = sub["ad_revenue"].sum()
    total_shop_rev = sub["shopify_revenue"].sum()
    gap = total_ad_rev - total_shop_rev
    pct = 100 * gap / total_ad_rev if total_ad_rev else 0
    status = "pass" if abs(pct) < 10 else ("warn" if abs(pct) < 40 else "fail")
    return {
        "check": "ad_platform_vs_shopify_revenue_discrepancy",
        "status": status,
        "issue_count": 1 if status != "pass" else 0,
        "details": (
            f"Bing+Google (the only platforms with a revenue field): ad platforms report "
            f"${total_ad_rev:,.2f}, Shopify shows ${total_shop_rev:,.2f} ({pct:+.1f}% gap)."
        ),
    }


RECONCILIATION_CHECKS = [
    check_ga4_join_coverage,
    check_shopify_join_coverage,
    check_session_click_ratio_outliers,
    check_conversion_discrepancy,
    check_revenue_discrepancy,
]


# ---------------------------------------------------------------------------
# 7. MAIN
# ---------------------------------------------------------------------------

def run_pipeline(bing_path: str, google_path: str, meta_path: str, outdir: str,
                  ga4_path: str = None, shopify_path: str = None):
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    frames = [
        load_bing(bing_path),
        load_google_ads(google_path),
        load_meta_ads(meta_path),
    ]
    df = pd.concat(frames, ignore_index=True)
    df = add_derived_fields(df)

    report = {"row_count": len(df), "platforms": df["platform"].value_counts().to_dict(), "checks": []}
    for check_fn in VALIDATION_CHECKS:
        result = check_fn(df)
        report["checks"].append(result)

    recon_monthly = build_reconciliation_summary(df)

    # Write unified dataset (drop internal helper column before export)
    export_df = df.drop(columns=["_name_valid"])
    export_df.to_csv(outdir / "unified_campaign_data.csv", index=False)
    recon_monthly.to_csv(outdir / "reconciliation_monthly_summary.csv", index=False)

    channel_recon = None
    if ga4_path and shopify_path:
        ga4_df = load_ga4_sessions(ga4_path)
        shopify_df = load_shopify_orders(shopify_path)
        channel_recon = build_channel_reconciliation(df, ga4_df, shopify_df)
        channel_recon.to_csv(outdir / "channel_reconciliation.csv", index=False)
        for check_fn in RECONCILIATION_CHECKS:
            report["checks"].append(check_fn(channel_recon))

    with open(outdir / "validation_report.json", "w") as f:
        json.dump(report, f, indent=2, default=str)

    write_text_report(report, outdir / "validation_report.txt")

    print(f"Unified dataset: {outdir / 'unified_campaign_data.csv'} ({len(export_df)} rows)")
    print(f"Ad-platform monthly summary: {outdir / 'reconciliation_monthly_summary.csv'}")
    if channel_recon is not None:
        print(f"Channel reconciliation (ad vs GA4 vs Shopify): {outdir / 'channel_reconciliation.csv'} "
              f"({len(channel_recon)} rows)")
    print(f"Validation report: {outdir / 'validation_report.json'} / .txt")
    n_fail = sum(1 for c in report["checks"] if c["status"] == "fail")
    n_warn = sum(1 for c in report["checks"] if c["status"] == "warn")
    print(f"Checks: {len(report['checks'])} total, {n_fail} failed, {n_warn} warnings")


def write_text_report(report: dict, path: Path):
    lines = [
        "DATA INGESTION / VALIDATION / RECONCILIATION REPORT",
        "=" * 55,
        f"Total rows ingested: {report['row_count']}",
        f"Rows by platform: {report['platforms']}",
        "",
    ]
    for c in report["checks"]:
        lines.append(f"[{c['status'].upper()}] {c['check']} -- {c['issue_count']} issue(s)")
        details = c["details"]
        if isinstance(details, list):
            for d in details[:10]:
                lines.append(f"    - {d}")
        elif isinstance(details, dict):
            for k, v in details.items():
                lines.append(f"    - {k}: {v}")
        elif details:
            lines.append(f"    - {details}")
        lines.append("")
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bing", default="bing_campaign_stats.csv")
    parser.add_argument("--google", default="google_ads_campaign_stats.csv")
    parser.add_argument("--meta", default="meta_ads_campaign_stats.csv")
    parser.add_argument("--ga4", default="synthetic_ga4_sessions.csv",
                         help="GA4 sessions CSV (date, channel_grouping, sessions, ...)")
    parser.add_argument("--shopify", default="synthetic_shopify_orders.csv",
                         help="Shopify orders CSV (order_date, channel_grouping, revenue, ...)")
    parser.add_argument("--skip-reconciliation", action="store_true",
                         help="Run ad-platform-only validation, skip GA4/Shopify entirely")
    parser.add_argument("--outdir", default="./output")
    args = parser.parse_args()

    run_pipeline(
        args.bing, args.google, args.meta, args.outdir,
        ga4_path=None if args.skip_reconciliation else args.ga4,
        shopify_path=None if args.skip_reconciliation else args.shopify,
    )
